remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Aave meets Twitter: Predicting the price of cryptocurrency using social sentiment analysis
description: The page of Yutong Quan's STATS201 Introduction to machine learning for social science Final Project
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
