plugins:
- jemoji
- jekyll-remote-theme
remote_theme: pages-themes/cayman@v0.2.0
title: Aave meets Twitter: Predicting the price of cryptocurrency using social sentiment analysis
description: The page of Yutong Quan's STATS201 Introduction to Machine Learning for Social Science Final Project
